### PR TITLE
Adding support for sensors Digoo DG-R8S with TFA (similar to Nexus) protocol

### PR DESCRIPTION
**Pull request by StalkerSVR**
Also added ID and channel tags to MQTT message for simplify of message routing in NodeRed

### CODE REVIEW

**Comment by aquaticus** [comment]
Do you have any description of TFA protocol?

**Comment by dpomparau** [comment]
Greatly appreciated if support for digoo Dg-r8s will be added 👍

**Comment by aquaticus** [comment]
Unfortunately I have no DG-R8S sensor and cannot test the code with this device.

**Comment by dpomparau** [comment]
I want to help with that. I can send you ~5$ or a sensor if you're in the neighborhood.

**Comment by aquaticus** [comment]
Thanks for the support :-)
I can prepare a version of the program that supports Digoo DG-R8S. If you agree to test it we can proceed this way.

**Comment by dpomparau** [comment]
Gladly! For the moment I have 2 sensors  and can get another 2.

**Comment by pigeon** [comment]
@dpomparau have you tried testing this PR on the devices?

**Comment by dpomparau** [comment]
No, sorry, just Digoo DG-R8S and Digoo DG-R8H.

**Comment by pigeon** [comment]
Oh sorry, I meant Digoo DG-R8S. Has it worked for you?

**Comment by dpomparau** [comment]
Yes, with this change it works. I saw some difference between R8s and R8h at humidity values but the program works without issues.

**Comment by pigeon** [comment]
Great. Thanks. Trying it with the same devices as we speak.

**Comment by aquaticus** [comment]
Breaks compatibility with existing sensor. Will reuse it when support for multiple sensor types added.

**Pull request closed without merging**
